### ISSUE TITLE
Hope you add srt subtitle translation ,its useful

### ISSUE THREAD

**Issue by ilovebody** [ffreemt/deepl-tr-electron#1]
good job

**Comment by ffreemt** [comment]
I took a look at the official deepl website.  I believe `deepl-tr-electron` can already handle most part of a srt file properly except those with tags, for example
```
<i>Tonight's the night.</i>
```
in which case you'll just have to preprocess and postprocess those tags. For example, replace `<i>` with `i_ ` and `</i>` with ` _i` before sending to `deepl-tr-electron`  and retore the `<i>` and `</i>` after  `deepl-tr-electron` finishes the translation. 

You can use `*.srt` to show srt files when loading a file. I'll add the `srt` suffix to default seleccted files in next update.

**Comment by ffreemt** [comment]
In fact, replacing `<i>` with `<_i>` is enough. deepl will properly handle
```
<_i>Tonight's the night.</i>
```
Just restore `<i>` afterwards.

I'll see whether I can implement a mechanism to do this automatically in next update.
